### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by rohank05** [matthew1232/discord-webhook-node#22]
I get this error while using it
internal/modules/cjs/loader.js:984
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\user\Desktop\--master\Mix Bot\node_modules\discord-webhook-node\src\index.mjs
[90m    at Module.load (internal/modules/cjs/loader.js:984:11)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\user\Desktop\--master\Mix Bot\start.js:4:21)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'ERR_REQUIRE_ESM'[39m
}

**Comment by matthew1232** [comment]
Can you try updating to 1.1.8 and let me know if the problem persists?
